services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3SitemapRobots\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'
      - '../Classes/Exception/*'
      - '../Classes/Extension.php'

  EliasHaeussler\Typo3SitemapRobots\Resource\RobotsTxtEnhancer:
    arguments:
      $sitemapLocator: '@sitemap_robots.sitemap_locator_without_robots_txt_provider'

  sitemap_robots.sitemap_locator_without_robots_txt_provider:
    class: 'EliasHaeussler\Typo3SitemapLocator\Sitemap\SitemapLocator'
  # @todo Enable once support for TYPO3 v11 is dropped
  #   arguments:
  #     $providers: !tagged_iterator { tag: 'sitemap_locator.sitemap_provider', default_priority_method: 'getPriority', exclude: ['EliasHaeussler\Typo3SitemapLocator\Sitemap\Provider\RobotsTxtProvider'] }
