services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3SitemapRobots\:
    resource: '../Classes/*'

  EliasHaeussler\Typo3SitemapRobots\Resource\RobotsTxtEnhancer:
    arguments:
      $sitemapLocator: '@sitemap_robots.sitemap_locator_without_robots_txt_provider'

  sitemap_robots.sitemap_locator_without_robots_txt_provider:
    class: 'EliasHaeussler\Typo3SitemapLocator\Sitemap\SitemapLocator'
    arguments:
      $providers: !tagged_iterator { tag: 'sitemap_locator.sitemap_provider', default_priority_method: 'getPriority', exclude: ['EliasHaeussler\Typo3SitemapLocator\Sitemap\Provider\RobotsTxtProvider'] }
