services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  EliasHaeussler\Typo3SitemapRobots\:
    resource: '../Classes/*'
    exclude:
      - '../Classes/DependencyInjection/*'
      - '../Classes/Exception/*'
      - '../Classes/Extension.php'

  EliasHaeussler\Typo3SitemapLocator\Sitemap\SitemapLocator:
    public: true
    arguments:
      $providers: !tagged_iterator { tag: 'sitemap_locator.sitemap_provider', default_priority_method: 'getPriority', exclude: ['EliasHaeussler\Typo3SitemapLocator\Sitemap\Provider\RobotsTxtProvider'] }
