name: CI

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - main

permissions:
  contents: read

jobs:
  prepare:
    name: 'Prepare workflow'
    uses: eliashaeussler/gha/.github/workflows/preparation.yaml@24e339c643ee01a7e008b13e40bcee4155c479fa # 0.2.3

  checks:
    name: 'Checks'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    permissions:
      security-events: write

    uses: eliashaeussler/gha/.github/workflows/checks.yaml@24e339c643ee01a7e008b13e40bcee4155c479fa # 0.2.3
    with:
      # We use the minimum supported PHP version
      php-version: 8.2 # renovate-ignore

  tests:
    name: 'Tests (PHP ${{ matrix.php-version }}, TYPO3 ${{ matrix.typo3-version }} & ${{ matrix.dependencies }} dependencies)'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    strategy:
      fail-fast: false
      matrix:
        php-version: ["8.2", "8.3", "8.4", "8.5"]
        typo3-version: ["13.4", "14.3"]
        dependencies: ["highest", "lowest"]

    uses: eliashaeussler/gha/.github/workflows/composer-tests.yaml@24e339c643ee01a7e008b13e40bcee4155c479fa # 0.2.3
    with:
      php-version: ${{ matrix.php-version }}
      typo3-version: ${{ matrix.typo3-version }}
      dependencies: ${{ matrix.dependencies }}
      boot-mysql: true

  test-coverage:
    name: 'Test coverage'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' }}

    uses: eliashaeussler/gha/.github/workflows/composer-test-coverage.yaml@24e339c643ee01a7e008b13e40bcee4155c479fa # 0.2.3
    with:
      coverage-file: Build/tests/coverage/clover.xml
      boot-mysql: true

  crowdin:
    name: 'Synchronize with Crowdin'

    needs: [prepare]
    if: ${{ needs.prepare.outputs.continue == 'true' && github.ref_name == 'main' }}

    secrets:
      CROWDIN_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/crowdin.yaml@24e339c643ee01a7e008b13e40bcee4155c479fa # 0.2.3
    with:
      project-id: 629518
