name: 'Merge Renovate branch'

on:
  workflow_run: # zizmor: ignore[dangerous-triggers]
    workflows: [CI]
    types: [completed]
    branches: ['renovate/*']

permissions:
  contents: read

jobs:
  merge:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    secrets:
      MERGE_TOKEN: ${{ secrets.REBUILD_ASSETS_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/merge.yaml@170d5386aa8f68a00af7ac7683228ed390c501e6 # 0.4.5
