name: Release

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: 'Create release'

    permissions:
      contents: write

    secrets:
      TYPO3_API_TOKEN: ${{ secrets.TYPO3_API_TOKEN }}

    uses: eliashaeussler/gha/.github/workflows/extension-release.yaml@170d5386aa8f68a00af7ac7683228ed390c501e6 # 0.4.5
    with:
      php-version: 8.2 # renovate-ignore
      packaging-excludes-file: Build/release/packaging_exclude.php
